//
// Created by alberto on 21/04/2020.
//

#ifndef TBKP_TBKP_BB_DEFS_H
#define TBKP_TBKP_BB_DEFS_H

#define NO_TIMEBOMB_ITEM_TO_BRANCH -1
#define INITIAL_UB_PLACEHOLDER -1.0
#define INITIAL_LB_PLACEHOLDER 0.0

#endif //TBKP_TBKP_BB_DEFS_H
